services:
  url-postgres:
    image: postgres:16
    container_name: url-service-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend

  url-liquibase:
    image: liquibase/liquibase:4.29
    container_name: liquibase_url_service_runner
    depends_on:
      url-postgres:
        condition: service_healthy
    volumes:
      - ./url-service/migrations:/liquibase/changelog
    environment:
      LIQUIBASE_COMMAND_URL: jdbc:postgresql://url-postgres:5432/${POSTGRES_DB}
      LIQUIBASE_COMMAND_USERNAME: ${POSTGRES_USER}
      LIQUIBASE_COMMAND_PASSWORD: ${POSTGRES_PASSWORD}
      LIQUIBASE_COMMAND_CHANGELOG_FILE: changelog/changelog.xml
    command: [ "update" ]
    networks:
      - backend

  url-service:
    build:
      context: .
      dockerfile: url-service/Dockerfile
    container_name: url-service
    depends_on:
      url-postgres:
        condition: service_healthy
      url-liquibase:
        condition: service_completed_successfully
    restart: unless-stopped
    ports:
      - "${URL_SERVICE_PORT}:${URL_SERVICE_PORT}"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: url-postgres
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PORT: 5432
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      URL_SERVICE_PORT: ${URL_SERVICE_PORT}
      URL_SERVICE_HOST: ${URL_SERVICE_HOST}
      MODERATION_SERVICE_PORT: ${MODERATION_SERVICE_PORT}
      MODERATION_SERVICE_HOST: ${MODERATION_SERVICE_HOST}
      HTTP_READ_TIMEOUT: ${HTTP_READ_TIMEOUT}
      HTTP_CONNECT_TIMEOUT: ${HTTP_CONNECT_TIMEOUT}
    networks:
      - backend

  moderation-service:
    build:
      context: .
      dockerfile: moderation-service/Dockerfile
    container_name: moderation-service
    depends_on:
      url-service:
        condition: service_started
    restart: unless-stopped
    environment:
      MODERATION_SERVICE_PORT: ${MODERATION_SERVICE_PORT}
    networks:
      - backend

networks:
  backend:
    driver: bridge