apiVersion: v1
kind: Secret
metadata:
  name: url-shortener-secrets
  namespace: url-shortener-namespace
type: Opaque
stringData:
  POSTGRES_USER: change_me
  POSTGRES_PASSWORD: change_me_strong_password
