apiVersion: batch/v1
kind: Job
metadata:
  name: url-service-postgres-migration
  namespace: url-shortener-namespace
spec:
  backoffLimit: 3
  activeDeadlineSeconds: 600
  template:
    spec:
      restartPolicy: Never
      initContainers:
        - name: wait-for-db
          image: postgres:16
          command: ["sh", "-c", "until pg_isready -h $POSTGRES_HOST -p $POSTGRES_PORT -U $POSTGRES_USER; do sleep 3; done"]
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: url-shortener-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: url-service-config
                  key: POSTGRES_HOST
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: url-service-config
                  key: POSTGRES_PORT
      containers:
        - name: liquibase
          image: mkhalez/url-migration:0.2
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: url-service-config
                  key: POSTGRES_DB
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: url-service-config
                  key: POSTGRES_PORT
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: url-service-config
                  key: POSTGRES_HOST
            - name: LIQUIBASE_COMMAND_URL
              value: "jdbc:postgresql://$(POSTGRES_HOST):$(POSTGRES_PORT)/$(POSTGRES_DB)"
            - name: LIQUIBASE_COMMAND_USERNAME
              valueFrom:
                secretKeyRef:
                  name: url-shortener-secrets
                  key: POSTGRES_USER
            - name: LIQUIBASE_COMMAND_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: url-shortener-secrets
                  key: POSTGRES_PASSWORD
            - name: LIQUIBASE_COMMAND_CHANGELOG_FILE
              value: "changelog/changelog.xml"
          args: ["update"]