server:
  port: ${URL_SERVICE_PORT}

spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: url-service
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        default_batch_fetch_size: 50
        format_sql: true

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}


url:
  short-url-length: 6
  host: http://${URL_SERVICE_HOST}:${URL_SERVICE_PORT}/


moderation-client:
  base-url: http://${MODERATION_SERVICE_HOST}:${MODERATION_SERVICE_PORT}
  connection-timeout: ${HTTP_READ_TIMEOUT:3000}
  read-timeout: ${HTTP_CONNECT_TIMEOUT:3000}