spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: moderation-service

server:
  port: ${MODERATION_SERVICE_PORT}

app:
  moderation:
    banned-words:
      - spamm
      - slopp
      - booot

management:
  health:
    probes:
      enabled: true